<section class="admin-section">

    <h2>Administrar Productos</h2>
    <button class="add-item-button open-add-modal">Agregar Ítem</button>

    <table class="admin-table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Categoria</th>
                <th>Url Imagen</th>
                <th>Acciones</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach($products as $product) { ?>
                <tr>
                    <td><?= htmlspecialchars($product->nombre) ?></td>
                    <td><?= htmlspecialchars($product->descripcion) ?></td>
                    <td><?= htmlspecialchars($product->precio) ?></td>
                    <td><?= htmlspecialchars($arrCategorys[$product->id_categoria]) ?></td>
                    <td><?=htmlspecialchars($product->URL_imagen)?></td>
                    <td>
                        <button class="add-item-button open-edit-modal" 
                                data-id="<?= htmlspecialchars($product->id_producto) ?>" 
                                data-nombre="<?= htmlspecialchars($product->nombre) ?>" 
                                data-descripcion="<?= htmlspecialchars($product->descripcion) ?>" 
                                data-precio="<?= htmlspecialchars($product->precio) ?>"
                                data-imagen="<?= htmlspecialchars($product->URL_imagen) ?>"
                                data-categoria-id="<?= htmlspecialchars($product->id_categoria) ?>">Editar</button>
                        <button class="add-item-button"><a href="eliminar_producto/<?= $product->id_producto ?>" class="add-item-button">Borrar</a></button>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</section>

<div id="agregarProductoModal" class="modal">
    <div class="modal-content">
        <h2>Agregar Ítem</h2>
        <form action="nuevo_producto" method="POST">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required>
            <br>
            <label for="descripcion">Descripción:</label>
            <textarea id="descripcion" name="descripcion" required></textarea>
            <br>
            <label for="precio">Precio:</label>
            <input type="number" id="precio" name="precio" required>
            <br>
            <label for="URL_imagen">URL Imagen:</label>
            <input type="text" id="URL_imagen" name="URL_imagen" required>
            <br>
            <label for="id_categoria">Categoría:</label>
            <select id="id_categoria" name="id_categoria" required>
                <option value="" disabled selected>Selecciona una categoría</option>
                    <?php foreach ($categorys as $category) { ?>
                <option value="<?= $category->id_categoria ?>"><?= htmlspecialchars($category->nombre) ?></option>
                    <?php } ?>
            </select>
            <br>
            <button type="submit">Agregar</button>
        </form>
    </div>
</div>

<div id="editarProductoModal" class="modal">
    <div class="modal-content">
        <h2>Editar Ítem</h2>
        <form method="POST" action="" id="editarFormulario">
            <input type="hidden" name="id_producto" id="editar_id_producto">
            <label for="editar_nombre">Nombre:</label>
            <input type="text" id="editar_nombre" name="nombre" required>
            <br>
            <label for="editar_descripcion">Descripción:</label>
            <input type="text" id="editar_descripcion" name="descripcion" required>
            <br>
            <label for="editar_precio">Precio:</label>
            <input type="number" id="editar_precio" name="precio" required>
            <br>
            <label for="editar_imagen">Url Imagen:</label>
            <input type="text" id="editar_imagen" name="URL_imagen" required>
            <br>
            <button type="submit">Guardar Cambios</button>
        </form>
    </div>
</div>

<script>
    // Abrir el modal de agregar ítem
    document.querySelector('.open-add-modal').addEventListener('click', function() {
        document.getElementById('agregarProductoModal').style.display = 'block';
    });

    // Abrir el modal de editar ítem
    let btnEditar = document.querySelectorAll('.open-edit-modal');
    btnEditar.forEach(button => {
        button.addEventListener('click', function() {
            let id = this.getAttribute('data-id');
            let nombre = this.getAttribute('data-nombre');
            let descripcion = this.getAttribute('data-descripcion');
            let precio = this.getAttribute('data-precio');
            let imagen = this.getAttribute('data-imagen');

            // Cargar los valores del producto en los campos del modal
            document.getElementById('editar_id_producto').value = id;
            document.getElementById('editar_nombre').value = nombre;
            document.getElementById('editar_descripcion').value = descripcion;
            document.getElementById('editar_precio').value = precio;
            document.getElementById('editar_imagen').value = imagen;
            
            // Establecer la acción del formulario de edición
            document.getElementById('editarFormulario').action = "editar_producto/" + id;

            // Mostrar el modal
            document.getElementById('editarProductoModal').style.display = 'block';
        });
    });

    // Cerrar el modal si se hace clic fuera del contenido del modal
    window.addEventListener('click', function(event) {
        let modal = document.querySelectorAll('.modal');
        modal.forEach(modal => {
            if (event.target === modal) {
                modal.style.display = 'none';
            }
        });
    });
</script>