<?php require 'templates/layout/header.phtml';?>

<?php $arrCategorys = [];
foreach ($categorys as $category) {$arrCategorys[$category->id_categoria] = $category->nombre;}?>

<div class="items-section">
    <div class="items-container">
        <div class="item-card">
            <img src="<?= htmlspecialchars($product->URL_imagen) ?>" alt="<?= htmlspecialchars($product->nombre) ?>">
                <div class="item-card-content">
                    <h3><?= htmlspecialchars($product->nombre) ?></h3>
                    <p class="price">Precio: $<?= htmlspecialchars($product->precio) ?></p>
                    <p class="description"><?= htmlspecialchars($product->descripcion) ?></p>
                    <p class="category">Categoría: <?= htmlspecialchars($arrCategorys[$product->id_categoria]) ?></p>
                </div>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml';?>