<!DOCTYPE html>
<html lang="es" data-bs-theme="dark">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TPE Especial</title>
    <link rel="stylesheet" href="css/style.css">    
</head>

<?php 
if (session_status() === PHP_SESSION_NONE) {
    session_start(); // Inicia la sesión solo si no hay una activa
}
if (isset($_SESSION['ID_USER'])) {
    $user = $_SESSION['ID_USER'];
} else {
    $user = null;
}
?>

<header class="header">
    <div class="logo">
        <h1>Hamburguesería</h1>
    </div>
<?php if(!$user):?>
        <nav class="nav">
            <ul>
                <li>
                    <a class="btn" href="<?= BASE_URL . 'home' ?>">Inicio</a>
                </li> 
                <li>
                    <a class="btn" href="<?= BASE_URL . 'categorias' ?>">Categorias</a>
                </li>
            </ul>
        </nav>
        <div class="admin-button">
            <a href="<?= BASE_URL . 'showLogin' ?>">Acceder como Administrador</a>
        </div>

<?php else :?>
        <div class="admin-button">
            <a href="<?= BASE_URL . 'logout' ?>">Cerrar Sesion</a>
        </div>
<?php endif; ?>
</header>